### ISSUE TITLE
compatible with MM Blog?

### ISSUE THREAD

**Issue by stoplion** [jordanandree/middleman-api#2]
Getting errors when I install this gem with MM blog.

**Comment by jordanandree** [comment]
can you post the error log? I havent tested this at all with MM Blog, so that would help getting it compatible. Thanks!

**Comment by stoplion** [comment]
When trying to start MM I'm getting a 

```
Users/geoneo/Sites/Work/georgenorr.is.static/source/partials/_project_navigation.slim:3:in `block in   singletonclass': undefined method `previous_article' for nil:NilClass (NoMethodError)
```

Doesnt seem to like the current_article.previous_article

**Comment by jordanandree** [comment]
Just pushed some updates that works better with ignored files and and destination paths. If you could bundle middleman-api from this github repo and see if it works okay, then that would be awesome.

One thing that i should not in the readme is that the api extension should be activated in your `config.rb` after the blog extension is activated. The blog extension does stuff with ignored templates and such that the api extension needs to know about, so the load order is important.

**Comment by jordanandree** [comment]
closing since this extension has been rewritten. MM Blog should be tested against v0.2.0
