### ISSUE TITLE
Bundler could not find compatible versions for gem "activesupport"

### ISSUE THREAD

**Issue by pedrokost** [jordanandree/middleman-api#4]
```
Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    middleman (~> 3.3.7) ruby depends on
      middleman-core (= 3.3.7) ruby depends on
        activesupport (~> 4.1.0) ruby

    middleman-api (>= 0) ruby depends on
      activesupport (3.2.12)
```

**Comment by jordanandree** [comment]
middleman-api doesn't have any direct dependency on active support.
what does your `Gemfile.lock` look like?

**Comment by pedrokost** [comment]
Here is my [Gemfile.lock](https://gist.github.com/c1c3863c16490085864e)

Adding `gem "middleman-api"` to the Gemfile causes the above problem to surface.

**Comment by jordanandree** [comment]
Looks like github version of the gem wasn't up on Rubygems. thats now fixed with some dependency changes for middleman. should be able to bundle now
